version: '2'

services:

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./.docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    command: server /data

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >   # this will re-create all buckets deleting all previous existing data
      /bin/sh -c "
      /usr/bin/mc config host rm myminio;
      /usr/bin/mc config host add myminio http://minio:9000 accessKey secretKey;
      /usr/bin/mc rb --force myminio/bucket;
      /usr/bin/mc mb myminio/bucket;
      exit 0;
      "

volumes:
  postgres:
    driver: local
  minio:
    driver: local
